/*
Este proyecto esta dedicado al saltamontes Gregory, faro de luz y esperanza en la oscuridad, 
que nos recuerda que incluso en los momentos más difíciles, siempre hay un camino hacia adelante. 
Su espíritu resiliente y su capacidad para superar obstáculos nos inspiran a perseverar 
y a encontrar soluciones creativas a los desafíos que enfrentamos. 
Que su memoria nos guíe y nos motive a seguir adelante con determinación y optimismo.

                               ....                                                                 
                             ..........                                                             
                            .....:::....                                    ........                
                          .....::-==-:....                               ...........                
                   ............::-===-:...                               ............               
                    ............::--==-:..                            ...............               
                 .....::---:......:-----:...                 ........................               
                  ....::-====-:.....::----:..                .........................               
                   ..::--====--:....::-==--:....     ............................                   
                   ....::----==-::...::--==-:............:::----====++=--:.......                   
                    .....:::---==--:::::--==-:.......:::--=====+++*****+-:...                       
                    ......::::--===---:::--===-:..::---====++++++***##*+=-....                      
                   ........:::::-=====--:--=====---=====+++++++++******+=-....                      
           .................::::::-======---=======++==++++++++++******+=-....                      
        .....................::::::-===========+++++++++++++++++++++***+=-....                      
        ....::--------:::::::::::---=====++++++++++++++++++++++++++++++=-...                        
        ...:--===++++===========---======+++++++++++++++++++++++=======-:..                         
        ...::--===++++++++++++++===========++++++++++++++++++==---::::::.........                   
        .....::--===+++++++++++++================++++++++===--:::::::::::......                     
        .......::---===+++++++++++====+++++=============---::....::::::::........                   
          .........::-----============================----:.......::::::.........                   
           ................:::------====---------=--------:::........:::.........                   
                 ................:::::::....::--:::::::................::........                   
                    ........................:::::.......................:::.......                  
                                  ...........:::.......            ...............                  
                                    ...................              .............                  
                                         .......   ...                ............                  
                                                                                                                                                                                            
         ........      ..       ....         ....         ......  .........    ...   ...            
      ................................................. ...................................         
.  .....:---::::.....::::::...::----::......::---::::.....::----::.....:::::-:::.......::.....      
   ...:-==--====-:::-====-:::--===-==-::..:-===--===--:.:--==--==-::..-====--==--:...:---:...       
  ..:--==----=++=----++=-:::====---====-::===--:-====-::-==--::-===-::=++=--:-===-..:-==-:....      
  ..:-==-:...:==-----==-...-=+=-----==+=--==-:...:-===--==-:...:-===-:=+=-:..:-===:.-===-...        
   .:===-....:-=-----==:..:-=++=========-===-....:--==--==-.....:-==-:===:....:-==--===::...        
 ...:===-:...:===----==:..:-=+=-::::------==-:...:-===--==-:...:-===-:===:.....:======-:...         
 ...:--==-::-=++=----==:...:===--::-----::-==--:-=====-:-==--::-===-::-==:.....:-=++=-:....         
 ....::=======++=-::---:....:--======-::..--===--====-:.:-=======-::..-=-:......:-++=:.....         
   ...:-------==-::...........::----:.....:-------===-....::---::......:........:-==-:...           
   ..:--=----===-........................:-==----===-:........................:--==-:....           
   ...:--------::.......  .......     ....:---=----::..........   ............:---::.....           
   .....::::::.....                    .....:::::::......          ...    .....:::......            
     ............                      ...................                 .............   

*/

package ingsoftware.zeroshop;

import ingsoftware.zeroshop.config.DotEnvInitializer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

@EnableAsync
@EnableScheduling
@SpringBootApplication
public class ZeroShopApp {

    static {
        loadDotEnv();
    }

    public static void main(String[] args) {
        loadDotEnv();
        SpringApplication app = new SpringApplication(ZeroShopApp.class);
        app.addInitializers(new DotEnvInitializer());
        app.run(args);
    }

    public static void loadDotEnv() {
        try {
            Path envPath = Path.of(".env");
            if (!Files.exists(envPath)) {
                envPath = Path.of("../.env");
            }
            if (Files.exists(envPath)) {
                List<String> lines = Files.readAllLines(envPath);
                for (String line : lines) {
                    line = line.trim();
                    if (!line.isEmpty() && !line.startsWith("#") && line.contains("=")) {
                        int eq = line.indexOf('=');
                        String key = line.substring(0, eq).trim();
                        String value = line.substring(eq + 1).trim();
                        System.setProperty(key, value);
                    }
                }
            }
        } catch (Exception ignored) {
        }
    }
}
